server:
  port: 8085

spring:
  application:
    name: vehicle-rental-api

  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle_rental_db
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true